import { db } from "@/lib/db";
import { currentUser } from "@/lib/session";
import { googleConfigured } from "@/lib/env";
import QRCode from "qrcode";
import { linkPhone, testPush } from "../inbox/actions";
import { phoneServerUrl } from "@/lib/lan";

export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const user = await currentUser();
  const connections = user
    ? await db.connection.findMany({ where: { userId: user.id } })
    : [];
  const serverUrl = phoneServerUrl();
  const [liveCode, devices] = user
    ? await Promise.all([
        db.linkCode.findFirst({
          where: { userId: user.id, usedAt: null, expiresAt: { gt: new Date() } },
          orderBy: { createdAt: "desc" },
        }),
        db.device.count({ where: { userId: user.id } }),
      ])
    : [null, 0];

  return (
    <main>
      <h1>Settings</h1>
      <p className="lede">
        {user ? `Signed in as ${user.email}` : "Not signed in."}
      </p>

      <h2>Connected sources</h2>

      {connections.map((connection) => (
        <article key={connection.id} className="card">
          <div className="meta">
            <span className="tag">{connection.provider}</span>
            <span>
              {connection.lastSyncAt
                ? `last synced ${connection.lastSyncAt.toLocaleString("en-US", { dateStyle: "medium", timeStyle: "short" })}`
                : "never synced"}
            </span>
          </div>
          <h3>{connection.accountEmail}</h3>
          <p className="why">Read-only: Gmail and Calendar. ChiefStaff cannot send as you.</p>
        </article>
      ))}

      {connections.length === 0 && (
        <p className="empty">No sources connected yet.</p>
      )}

      {googleConfigured() ? (
        <a href="/api/auth/google">
          <button className="primary">
            {connections.length ? "Connect another account" : "Connect Google Workspace"}
          </button>
        </a>
      ) : (
        <p className="empty">
          Google OAuth is not configured. Set <code>GOOGLE_CLIENT_ID</code> and{" "}
          <code>GOOGLE_CLIENT_SECRET</code> in <code>.env</code> to enable it.
        </p>
      )}

      <h2>Phone</h2>
      <p className="why">
        {devices === 0
          ? "No phone linked. The brief arrives by push at your brief hour once one is."
          : `${devices} ${devices === 1 ? "phone" : "phones"} linked.`}
      </p>
      {devices > 0 && (
        <form action={testPush} style={{ marginBottom: 12 }}>
          <button>Send a test push</button>
        </form>
      )}
      {liveCode ? (
        <article className="card">
          <div className="meta">
            <span>expires {liveCode.expiresAt.toLocaleTimeString("en-US", { timeStyle: "short" })}</span>
          </div>
          <div style={{ display: "flex", gap: 20, alignItems: "center", flexWrap: "wrap" }}>
            <div
              style={{ width: 168, height: 168, flexShrink: 0, background: "#fff", padding: 8, borderRadius: 8 }}
              dangerouslySetInnerHTML={{
                // Generated by us from our own values; nothing user-supplied is in it.
                __html: await QRCode.toString(
                  `chiefstaff://link?server=${encodeURIComponent(serverUrl)}&code=${liveCode.code}`,
                  { type: "svg", margin: 0, color: { dark: "#111318", light: "#ffffff" } },
                ),
              }}
            />
            <div>
              <p className="why" style={{ marginBottom: 6 }}>
                <strong>Point the phone&rsquo;s camera at this.</strong> It opens ChiefStaff and links by itself.
              </p>
              <p className="why" style={{ marginBottom: 6 }}>Or type it in the app:</p>
              <h3 style={{ fontSize: 28, letterSpacing: "0.18em", fontVariantNumeric: "tabular-nums", margin: "0 0 4px" }}>
                {liveCode.code.slice(0, 3)} {liveCode.code.slice(3)}
              </h3>
              <p className="why" style={{ margin: 0 }}>Server: <code>{serverUrl}</code></p>
            </div>
          </div>
        </article>
      ) : (
        user && (
          <form action={linkPhone}>
            <button>{devices ? "Link another phone" : "Link your phone"}</button>
          </form>
        )
      )}

      <h2>What this reads</h2>
      <p className="why">
        Everything is read with your own Google credentials, so ChiefStaff can only ever see what
        you can see. It requests read-only scopes and holds no send or write permission. Drafts are
        generated for your approval and are never delivered by this system.
      </p>
    </main>
  );
}
